### ISSUE TITLE
调用FUI.Get会更改FairyGUI的子节点顺序，影响点击事件

### ISSUE THREAD

**Issue by samsonchen1989** [egametang/ET#104]
FUI.Get 在获取子GObject的时候，如果没有子FUI，在调用FUI.Add(FUI ui)时会调用gComponent.AddChild重新添加该子节点，FairyGUI检测到该节点存在，调用SetChildIndex改变该节点顺序，导致点击事件层级和FairyGUI编辑器中的不一致。

**Comment by egametang** [comment]
这个自己修改下吧，不再维护fgui了

**Comment by samsonchen1989** [comment]
好，附件是修改后的FUI.cs
[FUI.zip](https://github.com/egametang/ET/files/2684299/FUI.zip)
