### ISSUE TITLE
master打包切换到webgl就报错

### ISSUE THREAD

**Issue by terribleness** [egametang/ET#110]
Assets\Model\Module\Pathfinding\Recast\Serialization\JsonSerializer.cs(787,26): error CS0103: The name 'AstarData' does not exist in the current context

Assets\Model\Module\Pathfinding\AstarPathfindingProject\Core\AstarData.cs(40,11): error CS0246: The type or namespace name 'GridGraph' could not be found (are you missing a using directive or an assembly reference?)

Assets\Model\Module\Pathfinding\AstarPathfindingProject\Core\AstarData.cs(43,11): error CS0246: The type or namespace name 'PointGraph' could not be found (are you missing a using directive or an assembly reference?)

Assets\Model\Module\Pathfinding\AstarPathfindingProject\Core\AstarData.cs(45,11): error CS0246: The type or namespace name 'NavMeshGraph' could not be found (are you missing a using directive or an assembly reference?)

Assets\Model\Module\Pathfinding\AstarPathfindingProject\Core\AstarData.cs(47,11): error CS0246: The type or namespace name 'LayerGridGraph' could not be found (are you missing a using directive or an assembly reference?)

**Comment by egametang** [comment]
没有试过webgl，这是3d寻路插件报错，应该是这个插件不支持
