### ISSUE TITLE
发送内容为空的消息时接收方会报异常

### ISSUE THREAD

**Issue by slb1988** [egametang/ET#116]
![image](https://user-images.githubusercontent.com/1139777/54003706-0ebdec00-418e-11e9-9f9c-22e3ed2e9715.png)

当创建不包含额外内容的消息结构体，比如：
message C2M_ErrMessageTest // IActorLocationMessage
{
	int32 RpcId = 90;
	int64 ActorId = 93;
	int64 Id = 94;
}
由客户端或服务器发送后，接收方会在 this.packetSize < 3 这里报错； 实际packetSize 为2，当将3修改为1时，可正常运行。

想问下，这里加的阈值的意义是什么？如何修改来兼容空内容的消息。

**Comment by slb1988** [comment]
![image](https://user-images.githubusercontent.com/1139777/54003987-fe5a4100-418e-11e9-8967-d8e130255977.png)

补充下，在这一版本时还没有这个bug，更新到最新的版本才出现。

**Comment by egametang** [comment]
已修复
