### ISSUE TITLE
EventSystem的Add方法中，存在多余的foreach循环

### ISSUE THREAD

**Issue by Fzcpp** [egametang/ET#121]
在EventSystem.cs 的 void Add(DLLType,Assembly) 方法中，

foreach (Assembly value in this.assemblies.Values)

该循环是不必要的。

![image](https://user-images.githubusercontent.com/27774738/54672513-379d9400-4b33-11e9-988a-6854345e4e4c.png)

**Comment by AlunYjj** [comment]
https://bbs.honorworkroom.com/forum.php?mod=viewthread&tid=137&extra=page%3D1
已解答

**Comment by Fzcpp** [comment]
建议重构，每次Add的时候，使types数组增量变化即可，没必要每次都重刷。
