### ISSUE TITLE
关于玩家数据设计

### ISSUE THREAD

**Issue by zt897571** [egametang/ET#134]
如果玩家上线时从数据库拿出玩家的数据,假设名称为 PlayerEntity, 这个结构包含了玩家的各种数据，后面如果每次修改了以后都SaveDB一下，因为是整个PlayerEntity全部写入数据库，这样会不会导致数据库压力比较大，或者说专门开个Db服，玩家上线从Monogo拉取数据，玩家下线数据落地，这样的逻辑会好些吗？ 求解答，也欢迎大家提出自己的方案和想法

**Comment by egametang** [comment]
不需要每次改都写，定时写比如5分钟写一次

**Comment by zt897571** [comment]
这样不会导致瞬时cpu过高吗。如果同时在线人数多了 + 玩家数据量过大，应该会有明显的卡顿吧
