### ISSUE TITLE
unity 2018.211f1 打开报错 

### ISSUE THREAD

**Issue by Emerson92** [egametang/ET#140]
C:/Users/84675/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.package-manager-ui@2.0.7/Editor/Sources/Services/Upm/UpmBaseOperation.cs(33,34): error CS1061: Type `UnityEditor.PackageManager.PackageInfo' does not contain a definition for `author' and no extension method `author' of type `UnityEditor.PackageManager.PackageInfo' could be found. Are you missing an assembly reference?

**Comment by Emerson92** [comment]
使用的是 ET-Branch_V5.0 分支

**Comment by egametang** [comment]
看运行指南啊，5.0要2018.3
