### ISSUE TITLE
建议与DOTS进行结合

### ISSUE THREAD

**Issue by jiangwei007** [egametang/ET#142]
Unity最新的DOTS带来了几个优势：1、ECS结构  2、Burst编译方式   3、与Job System 更好的结合，所以建议ET的Component和System结构可以与DOTS的ECS结合，这更便于ET的推广和发展

**Comment by egametang** [comment]
没有意义，job是多线程的，不适合写逻辑，burst限制太多，纯ecs开发不方便。这三个东西牺牲了太多开发的方便性。ET目前这个设计是最方便写逻辑的
