### ISSUE TITLE
Error building Player: Currently selected scripting backend (IL2CPP) is not installed.

### ISSUE THREAD

**Issue by mar-sir** [egametang/ET#145]
Error building Player: Currently selected scripting backend (IL2CPP) is not installed.

**Comment by mar-sir** [comment]
我看设置Scripting Backend的选项都不可以选，是灰色的

**Comment by xiajjjjjjjjjj** [comment]
你怕是没有安装 IL2CPP的构建器

**Comment by ahmedaniss25** [comment]
https://youtu.be/g3bcWMuHo9Y

**Comment by ahmedaniss25** [comment]
Problem fixed here : https://youtu.be/g3bcWMuHo9Y
