### ISSUE TITLE
(MacOS下)命令行工具，启动server，提示错误

### ISSUE THREAD

**Issue by sekkit** [egametang/ET#152]
server已经用visual studio for mac编译成功。

Win32Exception: ApplicationName='dotnet', CommandLine='App.dll --appId=1 --appType=Manager --config=../Config/StartConfig/127.0.0.1.txt', CurrentDirectory='../Bin/', Native error= Cannot find the specified file

**Comment by taurushz** [comment]
遇到一样的问题

**Comment by zhuxiaobin555** [comment]
你试一下直接打开server.sln启动服务器试一下。我的也是Win32Exception: 系统找不到指定的文件。直接打开server启动就好了
