### ISSUE TITLE
适配Android ARM64

### ISSUE THREAD

**Issue by mkanglonggithub** [egametang/ET#154]
请问可以适配一下arm64-v8a吗，好像主要是kcp的库要做一下适配，但是我拿到kcp的源码https://github.com/skywind3000/kcp
编译出的arm64的so库使用起来有问题，在发起请求C2R_Login的时候，服务端收到请求并reply()了，但是客户端却卡在这个请求里了，除非我退出游戏，代码才会继续往下执行（因为打出了日志）

**Comment by egametang** [comment]
用我账号下那个kcp库编译

**Comment by mkanglonggithub** [comment]
谢谢，已解决~
