### ISSUE TITLE
5.0基准测试问题

### ISSUE THREAD

**Issue by chanayy123** [egametang/ET#173]
1 TCP协议测试:  在模拟客户端进程刚启动时，大量创建连接session,如果强制关掉客户端进程，服务器大概率会收到异常 accept error ConnectionReset,如果延迟几秒钟再关客户端就没问题
2 websocket测试: 不管是客户端一个连接发多次ping还是多个连接发多次Ping,在强制关掉客户端进程,服务器都会在receiveAsync都会捕获异常 System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.  ---> System.Net.HttpListenerException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
注: 如果用js客户端发送websocket协议,强制关闭是没有问题的。

**Comment by egametang** [comment]
这种报错如果不影响就不用处理了，本来就是异常情况，如果处理也仅仅是try 一下，没有意义

**Comment by chanayy123** [comment]
嗯呢 有道理!
