### ISSUE TITLE
master客户端下载ab包有点问题

### ISSUE THREAD

**Issue by honggu025** [egametang/ET#174]
`public class BundleDownloaderComponent : Entity`
这个类文件的第67行
`using (UnityWebRequestAsync webRequestAsync = EntityFactory.Create<UnityWebRequestAsync>(this.Domain))`
以前用的是ComponentFactory，现在用的是EntityFactory，而EntityFactory.Create在创建对象的时候，会把实参（this.Domain）赋值给新建对象的Domain属性，赋值时会判断value是否继承自Scene，不是就抛出异常，通过调试，这个实参(this.Domain)不是继承自Scene，而是null，所以运行到这里就会异常，导致下载不成功。

**Comment by egametang** [comment]
6.0先不要使用，暂时不能稳定
