### ISSUE TITLE
跨域继承的类，在async方法中使用Dictionary的TryGetValue()，只能获取到适配器类

### ISSUE THREAD

**Issue by 0lfh0** [egametang/ET#188]
public class Student : ETModel.Protocol.IProtocol  //跨域继承接口
        {
            public string Name { get; set; }
            public int Age { get; set; }
        }

        private static Dictionary<string, Student> sts = new Dictionary<string, Student>(); //测试字典

        //开始测试
        private static void StartTest()   
        {
            sts.Add("one", new Student());
            Test();
            TestAsync().Coroutine();
        }

        //测试普通方法
        private static void Test()   
        {
            if (sts.TryGetValue("one", out Student st))
            {
                Log.Warning($"Test: {st.GetType()}");  //这里打印的是Test: Type: Student
            }
        }

       //测试异步方法
        private static async ETVoid TestAsync() 
        {
            if (sts.TryGetValue("one", out Student st))
            {
                //这里打印的是TestAsync: ETModel.IProtocolClassInheritanceAdaptor+IProtocolAdaptor
                Log.Warning($"TestAsync: {st.GetType()}"); 
            }
            Test2();
            await ETTask.CompletedTask;
        }

        private static void Test2()
        {
            if (sts.TryGetValue("one", out Student st))
            {
                Log.Warning($"Test2: {st.GetType()}"); //这里也是正常的， 打印的是Test: Type: Student
            }
        }

**Comment by egametang** [comment]
跨域继承，ET不推荐也不支持

**Comment by 28106830** [comment]
跨域不好操作，也不太好理解
我强制自己写时：所有数据全部在model层，hotfix层只管逻辑
如果你都要改数据结构了，可认为要停服更新
