### ISSUE TITLE
找不到ET/Unity/Unity.*.csproj项目文件

### ISSUE THREAD

**Issue by ryuujo1573** [egametang/ET#242]
[https://github.com/egametang/ET/blob/master/Book/1.1%E8%BF%90%E8%A1%8C%E6%8C%87%E5%8D%97.md](url)
## 问题再现
> # 运行步骤
> ...
> 3. 启动unity， 菜单 File->open project->open 选中ET/Unity文件夹，点击选择文件夹按钮。
> 4.点击Unity菜单Assets->open C# project启动vs 编译（一定要编译，右键VS解决方案，全部编译）
>
第四步出错：
![image](https://user-images.githubusercontent.com/16525512/119502567-a3778900-bd9c-11eb-8cc8-23fe4b977038.png)
在repo里也没有这几个项目文件，是不是哪里出问题了？

## 其他信息
环境：macOS, Unity 2021.1.7f1c1.

**Comment by egametang** [comment]
可以去群里问问，这是unity生成的
