### ISSUE TITLE
Generate CLR Binding Code by Analysis 错误问题

### ISSUE THREAD

**Issue by qq464418017** [egametang/ET#280]
TypeLoadException: Cannot find Adaptor for:System.Collections.Generic.IComparer`1[ILRuntime.Runtime.Intepreter.ILTypeInstance]
ILRuntime.CLR.TypeSystem.ILType.InitializeInterfaces () (at Assets/ThirdParty/ILRuntime/ILRuntime/CLR/TypeSystem/ILType.cs:510)
ILRuntime.CLR.TypeSystem.ILType.get_FirstCLRInterface () (at Assets/ThirdParty/ILRuntime/ILRuntime/CLR/TypeSystem/ILType.cs:188)
ILRuntime.CLR.TypeSystem.ILType.get_TypeForCLR () (at Assets/ThirdParty/ILRuntime/ILRuntime/CLR/TypeSystem/ILType.cs:399)
ILRuntime.Runtime.CLRBinding.BindingCodeGenerator.CrawlAppdomain (ILRuntime.Runtime.Enviorment.AppDomain domain, System.Collections.Generic.Dictionary`2[TKey,TValue] infos) (at Assets/ThirdParty/ILRuntime/ILRuntime/Runtime/CLRBinding/BindingCodeGenerator.cs:373)
ILRuntime.Runtime.CLRBinding.BindingCodeGenerator.GenerateBindingCode (ILRuntime.Runtime.Enviorment.AppDomain domain, System.String outputPath, System.Collections.Generic.List`1[T] valueTypeBinders, System.Collections.Generic.List`1[T] delegateTypes) (at Assets/ThirdParty/ILRuntime/ILRuntime/Runtime/CLRBinding/BindingCodeGenerator.cs:166)
ILRuntimeCLRBinding.GenerateCLRBindingByAnalysis () (at Assets/Editor/ILRuntimeEditor/ILRuntimeCLRBinding.cs:64)

**Comment by egametang** [comment]
最新版热更已经加上
