### ISSUE TITLE
喜大普奔6.0终于面世了，可是卡在了运行指南...

### ISSUE THREAD

**Issue by chanayy123** [egametang/ET#286]
目前本子用的macOS系统，在升级net6.0之前的环境都挺好的，当前最新分支用vs2022 for mac打开client-server.sln，client目录是空的还有其他一些怪问题，换成rider2.2，
清理解决方案每个项目都会显示警告   Microsoft.NET.Sdk.DefaultItems.targets(134, 5): [NETSDK1182] 不支持在 Visual Studio 2019 中以 .NET 6.0 为目标。
构建解决方案会报错：An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.0/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll : Could not resolve type with token 01000027 from typeref (expected class 'Microsoft.CodeAnalysis.IIncrementalGenerator' in assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35') assembly:Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:Microsoft.CodeAnalysis.IIncrementalGenerator member:(null).
网上搜了下大概是因为项目的某些设置和最新的.net6不兼容，不知道是不是只有macos版才这样，Windows没有试过！

**Comment by egametang** [comment]
用rider
