### ISSUE TITLE
LitJson中的[JsonIgnore]没有作用

### ISSUE THREAD

**Issue by rekcah1986** [egametang/ET#339]
![image](https://user-images.githubusercontent.com/3055444/165456154-9a282093-f6be-4e9c-8a00-32c896570ac1.png)

代码里只有定义，没有调用和实现，请问是没写完吗？

**Comment by egametang** [comment]
客户端的json目前只用来做消息日志输出，用的不多，其实用pb就够了

**Comment by rekcah1986** [comment]
> 

我是把Json用来做存档和配置读写的，已经找到了解决方法，改用[IgnoreDataMember]就可以了
