### ISSUE TITLE
UnityWebRequestAsync组件少了个IAwake接口

### ISSUE THREAD

**Issue by lamatimo** [egametang/ET#340]
self.AddComponent<UnityWebRequestAsync>();

提示
The type 'ET.UnityWebRequestAsync' must be convertible to 'ET.IAwake' in order to use it as parameter 'K' in the generic method 'K ET.Entity.AddComponent<K>(bool)'

**Comment by egametang** [comment]
已修复

**Comment by lamatimo** [comment]
收到
