### ISSUE TITLE
目前是否还未完善WebSocket部分内容

### ISSUE THREAD

**Issue by ishunsei** [egametang/ET#344]
参阅代码后发现Unity.Mono项目中WService的Get(long id, IPEndPoint address)方法尚未实现，Unity.Hotfix中也未找到有关于WebSocket的内容，是不是目前还未完成这部分内容呢？

**Comment by egametang** [comment]
是完整的，因为WebSocket不是用IPEndPoint连接的，是一个HTTP地址，所以只提供
protected void Get(long id, string address)方法
