### ISSUE TITLE
7.0 LitJson去掉以后JsonHelper不能解析结构体

### ISSUE THREAD

**Issue by lamatimo** [egametang/ET#377]
两个小问题:
1.去掉后不能解析为结构体了
2.解析不了以 id 为key的字符串 如 {\"id\": 100, \"X\": 1}

**Comment by egametang** [comment]
1.bson解析结构体需要注册一下，参考MongoHelper中注册Vector3的代码
2.bson的Id必须为: "_id"

**Comment by egametang** [comment]
如果需要用非严格模式解析json，参考ETBook里面mongo bson的文章

**Comment by lamatimo** [comment]
谢谢熊猫大大解惑 没仔细看ETBook里面的文章
