### ISSUE TITLE
我使用最新的master，打包运行报错：MissingMethodException: AOT generic method not instantiated in aot module. System.Void ET.AwakeSystem`2[ET.Session,System.Int32]::.ctor()

### ISSUE THREAD

**Issue by veainilo** [egametang/ET#424]
我使用最新的master，打包运行报错：MissingMethodException: AOT generic method not instantiated in aot module. System.Void ET.AwakeSystem`2[ET.Session,System.Int32]::.ctor()

**Comment by egametang** [comment]
HybridCLR用1.0版本的

**Comment by pirunxi** [comment]
这个问题刚刚在main分支，即2.x系列上修复了。

**Comment by veainilo** [comment]
问题已经解决

> HybridCLR用1.0版本的



> 这个问题刚刚在main分支，即2.x系列上修复了。
