### ISSUE TITLE
M2C_PathfindingResult消息可能比M2C_CreateUnits先到客户端

### ISSUE THREAD

**Issue by lamatimo** [egametang/ET#444]
![image](https://user-images.githubusercontent.com/42297620/225629930-22040de9-a7b9-4e60-b216-2a547e72d0ab.png)
unit可能还没有创建，获取不到，没有对unit做判空处理

**Comment by egametang** [comment]
不存在这种情况，如果出现，说明服务端写错了

**Comment by lamatimo** [comment]
![image](https://user-images.githubusercontent.com/42297620/225801768-dc78c050-f76c-4137-b23f-129d97819033.png)
![image](https://user-images.githubusercontent.com/42297620/225801839-26833bd6-6f28-49a5-a125-e0c11d5cd785.png)
B玩家进入视野，A玩家刚好寻路广播，此时A玩家BeSeePlayers包含了B玩家， 又因为UnitEnterSightRange事件是在协程处理，没有马上发送M2C_CreateUnits消息，是不是有这种可能

**Comment by egametang** [comment]
这个协程并不代表它在下一帧执行，其实里面没有await，它是同步执行的
