### ISSUE TITLE
组件设计.md里“接口逻辑难以复用”这种说法是错误的

### ISSUE THREAD

**Issue by fanhexin** [egametang/ET#46]
1. 接口逻辑复用只要通过**抽象类**来共享逻辑就可以了。

2. 觉得“难以热插拔”这样的说法也是有问题的。都抽象出接口了，当然可以在运行时进行热插拔。像文档里描述的骑马的情况，Player这个类是可骑行的，从描述上就是合理的，也不需要在运行时删除对这个接口的继承啊，一点逻辑代码而已，正常来说都不会携带额外数据。用接口究其原因还是为了解除耦合，隔离变化。你可以继承接口，当然也可以通过has a的关系将接口作为一个类的字段，都没问题，到头来还是看能不能活用。

**Comment by fanhexin** [comment]
另外再多说一句。组件设计作为面向对象编程范式的一种设计模式，本身就是面向对象的，不好与面向对象相提并论，讨论利弊。概念上组件设计是面向对象的子集。

**Comment by fanhexin** [comment]
其实应该讨论的是组件设计模式与传统只通过继承复用代码这样的设计模式之间的利弊。

**Comment by egametang** [comment]
1.相同逻辑放到抽象类，在复杂的继承体系是办不到的，这是你想的一种理想情况。由于只能单继承，很多情况下只能通过多接口来处理，所以才会有接口逻辑难以复用的说法
2.热插拔当然是需要的，因为逻辑可以这样判断，如果player可以骑行，那么骑行。player一直带着骑行接口，那么，这样就做不了，必须要多加额外的字段来实现。那么player身上必须一直带着这个额外的字段。我觉得很不优美。
3.面向对象三大特性，封装，继承，多态。ECS组件式设计在开发逻辑的时候字段都是public的，逻辑继承没有，逻辑多态没有，三大特性都没有或者很少有，不能算面向对象的子集。
