### ISSUE TITLE
Frame sync.

### ISSUE THREAD

**Issue by juliolitwin** [egametang/ET#465]
It was recently announced about framesync on ET, so as most of the information (forum and group) is all Chinese, it's hard to keep up. Could you provide more information?

How will the frame sync course work? Will it be paid or free? In the video you use a running example, will this example be public in git?

Cheers.

**Comment by TapsJoy** [comment]
It is paid.  And sorry my brother, the sync course is also in chinese.

**Comment by IcePower** [comment]
egametang said it will be public in git, but you may have to wait a few months。

**Comment by IcePower** [comment]
Now it's published  hahah
