### ISSUE TITLE
8.1分支中的新编译方式会导致UNITY_EDITOR宏失效。

### ISSUE THREAD

**Issue by Lead-NorthStar** [egametang/ET#556]
在接入YIUI的时候，YIUI的GM界面的打开是放在UNITY_EDITOR宏中的，在8.1通过快捷键的方式编译，会导致UNITY_EDITOR失效，从而无法GM相关逻辑。使用ET.sln在ide中编译则是正常的。
![image](https://github.com/egametang/ET/assets/139985926/c469cbf1-e5f7-4c29-bb3e-2c9811a2115e)

**Comment by Lead-NorthStar** [comment]
感觉是不是要多加个Debug编译模式之类的

**Comment by egametang** [comment]
用Define.IsEditor

**Comment by Lead-NorthStar** [comment]
好的，谢谢
