### ISSUE TITLE
给 ILocationRequest 加一个 LocationType 怎么样？

### ISSUE THREAD

**Issue by zerohualin** [egametang/ET#619]
```c#
    public interface ILocationRequest: IRequest
    {
        int LocationType 
        { 
            get => 0; // 默认值
            set { } // 空实现
        }
    }
```

创建消息的时候设置一下
```c#
var req = C2Lobby_EnterRoom.Create();
req.LocationType = LocationType.LobbyUnit;
```

分发的时候
```c#
MessageLocationSenderOneType sender = null;
if(actorLocationRequest.LocationType > 0)
   sender = root.GetComponent<MessageLocationSenderComponent>().Get(actorLocationRequest.LocationType);
else
   sender = root.GetComponent<MessageLocationSenderComponent>().Get(LocationType.Unit);
```

@egametang

**Comment by MrTigerZhang** [comment]
用起来麻烦 ，不直观。太隐晦。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月30日(星期二) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [egametang/ET] 给 ILocationRequest 加一个 LocationType 怎么样？ (Issue #619)














     public interface ILocationRequest: IRequest     {         int LocationType          {              get =&gt; 0; // 默认值             set { } // 空实现         }     }
 
分发的时候
                         MessageLocationSenderOneType sender = null;                         if(actorLocationRequest.LocationType &gt; 0)                             sender = root.GetComponent<MessageLocationSenderComponent&gt;().Get(actorLocationRequest.LocationType);                         else                             sender = root.GetComponent<MessageLocationSenderComponent&gt;().Get(LocationType.Unit);  
创建的时候设置一下
 var req = C2Lobby_EnterRoom.Create();             req.LocationType = LocationType.LobbyUnit;
