### ISSUE TITLE
Questions about server side scripting

### ISSUE THREAD

**Issue by MostHated** [egametang/ET#69]
Hello there,
    I have taken an interest in some of these C++ distributed entity frameworks I have seen here on github and had a question about the scripting backend. I use Unity3d for my game and currently my client and server side are separated but it is all written in C#. It is setup as authoritative so the client only sends requests to the server and then the server processes these requests and sends the result back to the clients for everything from movement, spellcasting, inventory, etc. I also use several 3rd party server-side assets which of course need to run on the server side, but are all also written in C#. Would I be able to use something like ET if all of my current server code is C#, or would everything have to be rewritten? I looked into KBEngine before, but you can only use python for the server side and I definitely do not want to have to rewrite everything  I already have, so I am trying to find something that might work for my particular case.

Thanks!
MostHated

**Comment by egametang** [comment]
if you use C#，you can move you old code to new framework like ET，but you need understand how to use the new framework。so i suggest you write entity framework by yourself。it only has few code
