### ISSUE TITLE
Dictionary 角标越界异常

### ISSUE THREAD

**Issue by zhangfengqwer** [egametang/ET#76]
` List<AccountInfo> accountInfos = await proxyComponent.QueryJson<AccountInfo>($"{{Third_Id:'{message.Third_Id}'}}");`
查询数据库的时候，报错
![default](https://user-images.githubusercontent.com/21104112/42267988-01b8c00a-7fad-11e8-95d5-5fdd9f609187.png)

**Comment by egametang** [comment]
什么版本？最新版本应该没有这个bug了

**Comment by zhangfengqwer** [comment]
3.2

**Comment by egametang** [comment]
更新，这个bug已经修复了
