### ISSUE TITLE
希望有大大写个et热更的教程.

### ISSUE THREAD

**Issue by 409544041** [egametang/ET#81]
热更小白.哪怕三句话都好.只要说明流程就行,原理,我可以慢慢看源码.,

**Comment by 409544041** [comment]
自己解决丰衣足食:
pc版资源热更:
第一步:
unity-tools-打包工具,勾选exe(用以生成pc版的可执行文件)
第二步
unity-tools-打包工具,不勾选exe(生成热更资源)
第三步
unity-tools-web资源服务器
第四步
当需要热更资源的时候,执行第二步生成热更资源.执行第一步生成的exe,就会自动热更资源了.

**Comment by Alunyjj** [comment]
很详细
